language: ruby
sudo: false
rvm:
- 2.2.3
branches:
  only:
  - master
addons:
  apt:
    packages:
    - imagemagick
    - wavpack
    - libsox-fmt-all
    - sox
    - shntool
    - mp3splt
    - libav-tools
    - make
    - g++
    - libsndfile1-dev
    - libpng++-dev
    - libpng12-dev
    - libboost-program-options-dev
before_install:

  # download, extract, and add ffmpeg and ffprobe to path
  - mkdir /tmp/ffmpeg
  - wget http://ffmpeg.gusari.org/static/64bit/ffmpeg.static.64bit.latest.tar.gz -O /tmp/ffmpeg/download-ffmpeg.tar.gz
  - tar -xzf /tmp/ffmpeg/download-ffmpeg.tar.gz -C /tmp/ffmpeg/
  - export PATH=/tmp/ffmpeg:$PATH

  # download, extract, and add wav2png to path
  - mkdir /tmp/wav2png
  - git clone https://github.com/beschulz/wav2png.git /tmp/wav2pnggit
  - make -C /tmp/wav2png/wav2pnggit/build all
  - mv /tmp/wav2png/wav2pnggit/bin/Linux/wav2png /tmp/wav2png/wav2png
  - export PATH=/tmp/wav2png:$PATH

  # check versions
  - which ffmpeg
  - ffmpeg -version
  - mp3splt -version
  - sox --version
  - wav2png --verion
script:
- bundle exec rspec
env:
  global:
    secure: alRlkr6JHTx8Op2G4S65JKot8k9zSuXEHHRu8ZqCk1uOrHVmEbljuN8kQhyNkM5vP4khwqSx64fPn4T8vBQCJ03cdsGQjO3SPR72ZdsYI4NLKD1tTu8yCn0n5w23LzLkY7IE5TwBH5XkuHjh0dGc7COWlc/F5Dnw3+o20Y5G1gA=
