language: ruby
rvm:
- 2.1.3
branches:
  only:
  - master
before_install:
- echo "Installing audio tools..."
- sudo apt-get update -qq
- sudo apt-get -y install imagemagick wavpack libsox-fmt-all sox shntool mp3splt libav-tools --fix-missing
- wget https://github.com/QutBioacoustics/baw-audio-tools/releases/download/v0.1.0/ffmpeg-git-20140817-64bit-static.tar.gz
- tar xvzf ffmpeg-git-20140817-64bit-static.tar.gz
- rm ffmpeg-git-20140817-64bit-static.tar.gz
- sudo mv ffmpeg /usr/local/bin
- sudo mv ffprobe /usr/local/bin
- sudo apt-get -y install make g++ libsndfile1-dev libpng++-dev libpng12-dev libboost-program-options-dev --fix-missing
- git clone https://github.com/beschulz/wav2png.git
- make -C ./wav2png/build all
- sudo mv ./wav2png/bin/Linux/wav2png /usr/local/bin
- echo "...testing for audio tools..."
- ffmpeg -version
- mp3splt -version
- sox --version
- wav2png --version
- echo "...audio tools installed."
- mkdir tmp
script:
- bundle exec rspec
env:
  global:
    secure: alRlkr6JHTx8Op2G4S65JKot8k9zSuXEHHRu8ZqCk1uOrHVmEbljuN8kQhyNkM5vP4khwqSx64fPn4T8vBQCJ03cdsGQjO3SPR72ZdsYI4NLKD1tTu8yCn0n5w23LzLkY7IE5TwBH5XkuHjh0dGc7COWlc/F5Dnw3+o20Y5G1gA=
