# Using SettingsLogic, see https://github.com/binarylogic/settingslogic
test:
  paths:
    image_magick_dir: <%= Dir.pwd %>/tmp/_image-magick
    original_audios:
      - <%= Dir.pwd %>/tmp/_original_audio
    cached_spectrograms:
      - <%= Dir.pwd %>/tmp/_cached_spectrogram
    cached_audios:
      - <%= Dir.pwd %>/tmp/_cached_audio
    analysis_scripts:
      - <%= Dir.pwd %>/tmp/_analysis_script
    analysis_results:
      - <%= Dir.pwd %>/tmp/_analysis_result
    analysis_runs:
      - <%= Dir.pwd %>/tmp/_analysis_run
    cached_datasets:
      - <%= Dir.pwd %>/tmp/_cached_dataset
    modules_log_file: <%= Dir.pwd %>/tmp/_modules_log.log
    temp_files: <%= Dir.pwd %>/tmp
  cached_audio_defaults:
    storage_format: mp3
    channel: 0
    sample_rate: 22050
    max_duration_seconds: 300.0
    min_duration_seconds: 0.5
  cached_spectrogram_defaults:
    storage_format: png
    channel: 0
    sample_rate: 22050
    window: 512
    colour: 'g'
    ppms: 0.045
    max_duration_seconds: 120.0
    min_duration_seconds: 0.5
  cached_dataset_defaults:
    storage_format: txt
    one_item_per_line: true
  available_formats:
    text:
      - json
    audio:
      - mp3
      - webm
      - ogg
      - flac
      - wav
    image:
      - png
  audio_tools:
    ffmpeg_executable: ffmpeg.exe
    ffprobe_executable: ffprobe.exe
    mp3splt_executable: mp3splt.exe
    sox_executable: sox.exe
    wavpack_executable: wvunpack.exe
    imagemagick_convert_executable: convert-im.exe
    imagemagick_identify_executable: identify-im.exe
    max_duration_seconds: 300
  audio_tools_timeout_sec: 10