# Using SettingsLogic, see https://github.com/binarylogic/settingslogic
test:
  paths:
    image_magick_dir: <%= File.dirname(__FILE__) %>/tmp/_image-magick
    original_audios:
      - <%= File.dirname(__FILE__) %>/tmp/_original_audio
    cached_spectrograms:
      - <%= File.dirname(__FILE__) %>/tmp/_cached_spectrogram
    cached_audios:
      - <%= File.dirname(__FILE__) %>/tmp/_cached_audio
    analysis_scripts:
      - <%= File.dirname(__FILE__) %>/tmp/_analysis_script
    analysis_results:
      - <%= File.dirname(__FILE__) %>/tmp/_analysis_result
    analysis_runs:
      - <%= File.dirname(__FILE__) %>/tmp/_analysis_run
    cached_datasets:
      - <%= File.dirname(__FILE__) %>/tmp/_cached_dataset
    modules_log_file: <%= File.dirname(__FILE__) %>/tmp/_modules_log.log
    temp_files: <%= File.dirname(__FILE__) %>/tmp
  cached_audio_defaults:
    storage_format: mp3
    channel: 0
    sample_rate: 22050
    max_duration_seconds: 300.0
    min_duration_seconds: 0.5
  cached_spectrogram_defaults:
    storage_format: png
    channel: 0
    sample_rate: 22050
    window: 512
    colour: 'g'
    ppms: 0.045
    max_duration_seconds: 120.0
    min_duration_seconds: 0.5
  cached_dataset_defaults:
    storage_format: txt
    one_item_per_line: true
  available_formats:
    text:
      - json
    audio:
      - mp3
      - webm
      - ogg
      - flac
      - wav
    image:
      - png
  audio_tools:
    ffmpeg_executable: ffmpeg
    ffprobe_executable: ffprobe
    mp3splt_executable: mp3splt
    sox_executable: sox
    wavpack_executable: wvunpack
    imagemagick_convert_executable: convert
    imagemagick_identify_executable: identify
    max_duration_seconds: 300
  audio_tools_timeout_sec: 20